### ISSUE TITLE
Bug in calling fetch for specific IDs

### ISSUE THREAD

**Issue by ChenyuanZ** [AWegnerGitHub/stackapi#29]
Hi,

I'm trying to use stackapi to fetch contents for specific IDs. Below is the traceback I got:
```Bash
>>> answers = SITE.fetch('/answers/{ids}/comments', ids=[1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/tools/miniconda3/envs/env_bot/lib/python3.6/site-packages/stackapi/stackapi.py", line 150, in fetch
    for k, value in kwargs.items():
RuntimeError: dictionary changed size during iteration
```
This error is caused by `stackapi/stackapi/stackapi.py` line 153
```Python
150 for k, value in kwargs.items():
151     if "{" + k + "}" in endpoint:
152         endpoint = endpoint.replace("{"+k+"}", ';'.join(requests.compat.quote_plus(str(x)) for x in value))
153         kwargs.pop(k, None) # kwargs size is changed during iteration
```
Could you help to solve this issue? I can create a pull request if you want to.

Thanks,
CY

**Comment by AWegnerGitHub** [comment]
Thank you for the bug report.

I just pushed a patch to both GitHub and PyPI. Version 0.1.9 should fix this issue for you.

**Comment by ChenyuanZ** [comment]
Thanks!
