### ISSUE TITLE
Got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by logankilpatrick** [AWegnerGitHub/stackapi#34]
```
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from stackapi import StackAPI
>>> SITE = StackAPI('stackoverflow')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/stackapi/stackapi.py", line 71, in __init__
    sites = self.fetch('sites', filter='!*L1*AY-85YllAr2)', pagesize=1000)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/stackapi/stackapi.py", line 183, in fetch
    response = requests.get(base_url, params=params, proxies=self.proxy)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 174, in send
    timeout=timeout
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 417, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 232, in _get_conn
    return conn or self._new_conn()
  File "/Users/logankilpatrick/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 547, in _new_conn
    strict=self.strict)
TypeError: __init__() got an unexpected keyword argument 'strict'

```

**Comment by AWegnerGitHub** [comment]
What version of `requests` are you using?

    >>> requests.__version__

**Comment by logankilpatrick** [comment]
```
>>> import requests

>>> 
>>> requests.__version__
'1.1.0'
```

**Comment by AWegnerGitHub** [comment]
Can you upgrade that? It looks like a bug before the 1.2.3 release.

If it helps, I am running 2.22.0

**Comment by logankilpatrick** [comment]
Thank you!
